const data = {
    products :[
        {
            _id:'1',
            name:'Bridal Lehenga',
            category:'Lehenga',
            image:'/images/p1.jpg',
            price:140,
            countInStock:10,
            brand:'Sabyasachi',
            rating:4.5,
            numReviews:10,
            description:'High quality product',
        },
        {
            _id:'2',
            name:'Bridal Lehenga',
            category:'Lehenga',
            image:'/images/p1.jpg',
            price:16,
            countInStock:0,
            brand:'Sabyasachi',
            rating:4.5,
            numReviews:14,
            description:'High quality product',
        },
        {
            _id:'3',
            name:'Bridal Lehenga',
            category:'Lehenga',
            image:'/images/p1.jpg',
            price:120,
            countInStock:17,
            brand:'Sabyasachi',
            rating:4.5,
            numReviews:16,
            description:'High quality product',
        },
        {
            _id:'4',
            name:'Bridal Lehenga',
            category:'Lehenga',
            image:'/images/p1.jpg',
            price:110,
            countInStock:0,
            brand:'Sabyasachi',
            rating:4.5,
            numReviews:17,
            description:'High quality product',
        },
        {
            _id:'5',
            name:'Bridal Lehenga',
            category:'Lehenga',
            image:'/images/p1.jpg',
            price:120,
            countInStock:17,
            brand:'Sabyasachi',
            rating:4.5,
            numReviews:18,
            description:'High quality product',
        },
        {
            _id:'6',
            name:'Bridal Lehenga',
            category:'Lehenga',
            image:'/images/p1.jpg',
            price:130,
            countInStock:16,
            brand:'Sabyasachi',
            rating:4.5,
            numReviews:19,
            description:'High quality product',
        },

    ],
};

export default data;